### ISSUE TITLE
Weights google link expired

### ISSUE THREAD

**Issue by rsingh2083** [Iterb/Detecting-tracking-and-counting-people#2]
Pls reshare the link for weights and config etc

**Comment by PuchalaS** [comment]
Unfortunately, I no longer have these weights. It was a project for my uni, and I deleted the files after passing it. To avoid confusion, I will remove the link from the repo. Alas, you will have to train the model yourself.

**Comment by rsingh2083** [comment]
Thanks for your reply, but there is lot of dataset on this link http://videodatasets.org/PAMELA-UANDES

Can you please help which ones to download ?
